### ISSUE TITLE
Setup QtGui error

### ISSUE THREAD

**Issue by diorn** [PrismPipeline/Prism#10]
Hi, I keep running in this error when i try to run prism setup on Linux mint, 
Prism was working ok a few days ago but i did some system restore and can't get it back working because of this install error

> Traceback (most recent call last):
>   File "Scripts/PrismInstaller.py", line 66, in <module>
>     from PySide.QtGui import *
> ImportError: No module named QtGui
> Traceback (most recent call last):
>   File "Scripts/PrismCore.py", line 69, in <module>
>     from PySide.QtGui import *
> ImportError: No module named QtGui

**Comment by monomon** [comment]
Try installing PySide from pip first:
`pip install PySide2`
