### ISSUE TITLE
Error when opening dialogs in Houdini

### ISSUE THREAD

**Issue by chrbir** [PrismPipeline/Prism#11]
Error when trying to open dialogs via the prism toolset in Houdini.

Windows 10
Houdini 17.5.360
Prism 1.2.0

**Errors for dialogs**

**Settings**

Traceback (most recent call last):
  File "C:/Prism\Scripts\PrismCore.py", line 211, in func_wrapper
    return func(*args, **kwargs)
  File "C:/Prism\Scripts\PrismCore.py", line 1107, in parentWindow
    win.setParent(self.messageParent, Qt.Window)
AttributeError: PrismCore instance has no attribute 'messageParent'

**State manager**

Traceback (most recent call last):
  File "C:/Prism\Scripts\PrismCore.py", line 211, in func_wrapper
    return func(*args, **kwargs)
  File "C:/Prism\Scripts\PrismCore.py", line 1189, in stateManager
    QMessageBox.warning(self.messageParent,"Warning (StateManager)", "Could not find project:\n%s" % os.path.dirname(os.path.dirname(curPrj)))
AttributeError: PrismCore instance has no attribute 'messageParent'

**Project browser**

Traceback (most recent call last):
  File "C:/Prism\Scripts\PrismCore.py", line 211, in func_wrapper
    return func(*args, **kwargs)
  File "C:/Prism\Scripts\PrismCore.py", line 1256, in projectBrowser
    QMessageBox.warning(self.messageParent,"Warning (ProjectBrowser)", "Could not find project:\n%s" % os.path.dirname(os.path.dirname(curPrj)))
AttributeError: PrismCore instance has no attribute 'messageParent'

**Save version comment**

Traceback (most recent call last):
  File "C:/Prism\Scripts\PrismCore.py", line 211, in func_wrapper
    return func(*args, **kwargs)
  File "C:/Prism\Scripts\PrismCore.py", line 2203, in saveWithComment
    QMessageBox.warning(self.messageParent,"Warning (StateManager)", "Could not find project:\n%s" % os.path.dirname(os.path.dirname(curPrj)))
AttributeError: PrismCore instance has no attribute 'messageParent'

**Save version**

Traceback (most recent call last):
  File "C:/Prism\Scripts\PrismCore.py", line 211, in func_wrapper
    return func(*args, **kwargs)
  File "C:/Prism\Scripts\PrismCore.py", line 2106, in saveScene
    QMessageBox.warning(self.messageParent,"Warning (SaveScene)", "Could not find project:\n%s" % os.path.dirname(os.path.dirname(curPrj)))
AttributeError: PrismCore instance has no attribute 'messageParent'

**Comment by chrbir** [comment]
Resolved
