### ISSUE TITLE
Installer does not see Blender on Linux (Ubuntu 18.04 LTS)

### ISSUE THREAD

**Issue by magdesign** [PrismPipeline/Prism#13]
**Describe the bug**
Prism installer does not see my Blender installs.
Since on Linux you unpack Blender and place the folder where ever you want (mostly `/opt/`)
Can not manually search my Blender bin files.

**To Reproduce**
unpack Prism_v1.2.0_Linux.tar.gz to /opt/Prism
`cd` into `/opt/Prism`
run `sudo ./Prism_setup_Linux.sh `

![prism_setup](https://user-images.githubusercontent.com/5273166/70382180-d4b98a80-1957-11ea-87ae-b4f7c6839dfe.png)

**Expected behavior**
I'd like to double click into the window to set my custom path to all of my Blender versions.

![Blender_versions](https://user-images.githubusercontent.com/5273166/70382187-1813f900-1958-11ea-8411-e1280bbde4a3.png)

**Desktop (please complete the following information):**
NAME="Pop!_OS"
VERSION="18.04 LTS"
ID=ubuntu
ID_LIKE=debian
Desktop_=XFCE4

**Comment by aditiapratama** [comment]
hi @magdesign how do you install Prism in PopOS!, I've got the following error with python pyside.

```sh
python3 "/opt/Pipeline/Prism/Scripts/PrismTray.py"
/opt/Pipeline/Prism/Scripts/PrismTray.py:197: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  curProject is not None and curProject is not ""
Traceback (most recent call last):
  File "/opt/Pipeline/Prism/Scripts/PrismTray.py", line 56, in <module>
    from PySide2.QtCore import *
ImportError: /opt/Pipeline/Prism/PythonLibs/Python37/PySide/PySide2/Qt/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libQt5Network.so.5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/Pipeline/Prism/Scripts/PrismTray.py", line 60, in <module>
    from PySide2.QtCore import *
ImportError: /opt/Pipeline/Prism/PythonLibs/Python37/PySide/PySide2/Qt/lib/libQt5Core.so.5: version `Qt_5.12' not found (required by /lib/x86_64-linux-gnu/libQt5Network.so.5)
```

**Comment by magdesign** [comment]
@aditiapratama 
Just tested on Pop!OS 20.04 LTS
and was not able to install!

I think there are some problems in with Python versions and PySide Versions.
See this issue here: https://github.com/RichardFrangenberg/Prism/issues/19

**Comment by aditiapratama** [comment]
I can install after updating with `sudo alternatives` method following this [tutorial](https://www.fosslinux.com/39384/switching-between-python-2-and-3-versions-on-ubuntu-20-04.htm)

but now another issue arise when starting PrismTray
<pre>python /opt/Pipeline/Prism/Scripts/PrismTray.py
/opt/Pipeline/Prism/Scripts/PrismTray.py:197: SyntaxWarning: &quot;is not&quot; with a literal. Did you mean &quot;!=&quot;?
  curProject is not None and curProject is not &quot;&quot;
Traceback (most recent call last):
  File &quot;/opt/Pipeline/Prism/Scripts/PrismTray.py&quot;, line 56, in &lt;module&gt;
    from PySide2.QtCore import *
ImportError: /opt/Pipeline/Prism/PythonLibs/Python37/PySide/PySide2/Qt/lib/libQt5Core.so.5: version `Qt_5.12&apos; not found (required by /lib/x86_64-linux-gnu/libQt5Network.so.5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/opt/Pipeline/Prism/Scripts/PrismTray.py&quot;, line 60, in &lt;module&gt;
    from PySide.QtCore import *
ModuleNotFoundError: No module named &apos;PySide.QtCore&apos;
</pre>

**Comment by magdesign** [comment]
Open a new issue and exactly describe all the errors including your OS version.

**Comment by monomon** [comment]
The issue that Blender was not showing up in the ui has been fixed in recent versions, it seems.
The logic searching for blender installations is still in need of some attention.
